### ISSUE TITLE
Support consumer group in Gemfire binder

### ISSUE THREAD

**Issue by mbogoevici** [spring-cloud/spring-cloud-stream-binder-gemfire#1]

**Comment by garyrussell** [comment]
@pperalta I see how you are distributing a copy of each message to each group, but it's not clear to me how group members compete for messages. The test only has one consumer per group.

I tried changing the test to start 2 consumers for each group [here](https://github.com/garyrussell/spring-cloud-stream-binder-gemfire/commit/445904f6941f7db561df4378fc995dfd6af9f2af) and the 3rd and fourth consumers don't receive a message ... but I am missing something because I don't see `Connected to Distributed System [] ...` for the third and fourth consumers.

**Comment by pperalta** [comment]
Hi @garyrussell,

Since the test right now only sends one message per group, only one VM will receive the message. The VM that receives the message will the the VM that happens to own the bucket for the key used to store the message in the partitioned region. I've slightly modified the test to have each producer send multiple messages to make sure that multiple buckets are used, and the test asserts that each consumer received at least one message.

See https://github.com/pperalta/spring-cloud-stream-binder-gemfire/commit/839ddf0b1650d1cb7742fa24725d5c16103c1c32

**Comment by garyrussell** [comment]
Thanks; but I am still trying to understand what happens when there are multiple consumers in the same group. Are the buckets somehow distributed across consumers in the same group?
